### ISSUE TITLE
XSS vulnerability

### ISSUE THREAD

**Issue by amir-zeldes** [Arborator/arborator-server#19]
The project parameter is not properly escaped in project.cgi, leading to a possible XSS vulnerability, e.g.:

```
<SERVER>/project.cgi?project=orpheo"><script>alert(150)</script>
```

**Comment by kimgerdes** [comment]
yes, this might be a problem, but afaik this doesn't allow access to the db queries. - however the db is not very secure for injections if someone wants to hack it at other points i suppose, especially if you have an admin account.
actually, the dev version was a (failed) attempt to get the whole project under flask where a new login scheme will be put into use. i should have marked it as not usable, but actually we have a new guy on it since a few weeks and i'm waiting for a first delivery any day now.
